<a href="https://colab.research.google.com/github/Akshay6249/Data-science-learning/blob/main/AGEING2ND_FILE_FULL_CODE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# Data cleaining in a Inventory Ageing stock file

1.   The excel files sperated in many sheets so merged into one.
2.   Removed numbers from some of the columns "sec","dep","cat"
3.Joined two columns and droped two columns
4.Filling na values in the data
5.List of values to be deleted
6.Converted into .csv

In [ ]:
import pandas as pd

# Specify the path to your input Excel file
input_excel_path = '/content/drive/MyDrive/CURRENT STOCK & AGEING STORE WISE.xlsx'

# Read all sheets from the input Excel file into a dictionary of DataFrames
xlsx = pd.ExcelFile(input_excel_path)
sheet_data = {}

for sheet_name in xlsx.sheet_names:
    df = pd.read_excel(xlsx, sheet_name)
    sheet_data[sheet_name] = df

# Create a new DataFrame by concatenating all the sheets
merged_data = pd.concat(sheet_data.values(), ignore_index=True)

# Specify the path and name for the output Excel file
output_excel_path = '/content/drive/MyDrive/AGEING 09-24-23.xlsx'

# Write the merged data to a new Excel file
merged_data.to_excel(output_excel_path, index=False)

print(f"All sheets merged and saved to '{output_excel_path}'.")

All sheets merged and saved to '/content/drive/MyDrive/AGEING 09-24-23.xlsx'.

In [ ]:
# Load Excel data into a pandas DataFrame
file_path = '/content/drive/MyDrive/AGEING 09-24-23.xlsx'  # Update with your file path
df = pd.read_excel(file_path)

# Display the DataFrame
print(df.head())

   SITE_ID   LOCATION   PARTY DEPT_NAME       SEC_NAME  \
0      461  COSTO KTN   S0068  1S01FMCG  1S0101GROCERY
1      461  COSTO KTN   R0003  1S01FMCG  1S0101GROCERY
2      461  COSTO KTN   A0214  1S01FMCG  1S0101GROCERY
3      461  COSTO KTN   A0214  1S01FMCG  1S0101GROCERY
4      461  COSTO KTN  KAJ001  1S01FMCG  1S0101GROCERY

                        CAT_NAME  PROD_CODE  SU  \
0  1S010115 CANNED / PACKED FISH     731940   1
1             1S010102COFFEE/TEA     775612   0
2              1S010108 BISCUITS     325966   8
3              1S010108 BISCUITS     318460   6
4             1S010102COFFEE/TEA     751620   0

                                  SU_DESCRIPTION      BRAND       BARCODE  \
0              PRINCESS SARDINE CHILLI 5 X 125GM   PRINCESS  2.000007e+12
1            DILMAH ENGLISH BREAKFAST TEA BAG 20     DILMAH  9.312631e+12
2  BRITANNIA GOOD DAY PISTA BADAM 2X8X72GM PROMO  BRITANNIA  6.291008e+12
3       BRITANNIA GOOD DAY CASHEW 2X8X72GM PROMO  BRITANNIA  6.291008e+12
4                      SIBLA DUST TEA BOX 450 GM      SIBLA  2.000007e+12

    SOH   VALUE  AGE_DAYS   SALE_AGE
0   8.0   8.800      19.0        NaN
1   6.0   4.878       3.0        NaN
2   4.0   7.232       1.0  21-SEP-23
3   6.0  10.806       1.0        NaN
4  24.0  15.360       5.0        NaN

In [ ]:
# Create a duplicate DataFrame
df_duplicate = df.copy()

# Display the original DataFrame
print("Original DataFrame:")
print(df.head())

# Display the duplicate DataFrame
print("\nDuplicate DataFrame:")
print(df_duplicate.head())

Original DataFrame:
   SITE_ID   LOCATION   PARTY DEPT_NAME       SEC_NAME  \
0      461  COSTO KTN   S0068  1S01FMCG  1S0101GROCERY
1      461  COSTO KTN   R0003  1S01FMCG  1S0101GROCERY
2      461  COSTO KTN   A0214  1S01FMCG  1S0101GROCERY
3      461  COSTO KTN   A0214  1S01FMCG  1S0101GROCERY
4      461  COSTO KTN  KAJ001  1S01FMCG  1S0101GROCERY

                        CAT_NAME  PROD_CODE  SU  \
0  1S010115 CANNED / PACKED FISH     731940   1
1             1S010102COFFEE/TEA     775612   0
2              1S010108 BISCUITS     325966   8
3              1S010108 BISCUITS     318460   6
4             1S010102COFFEE/TEA     751620   0

                                  SU_DESCRIPTION      BRAND       BARCODE  \
0              PRINCESS SARDINE CHILLI 5 X 125GM   PRINCESS  2.000007e+12
1            DILMAH ENGLISH BREAKFAST TEA BAG 20     DILMAH  9.312631e+12
2  BRITANNIA GOOD DAY PISTA BADAM 2X8X72GM PROMO  BRITANNIA  6.291008e+12
3       BRITANNIA GOOD DAY CASHEW 2X8X72GM PROMO  BRITANNIA  6.291008e+12
4                      SIBLA DUST TEA BOX 450 GM      SIBLA  2.000007e+12

    SOH   VALUE  AGE_DAYS   SALE_AGE
0   8.0   8.800      19.0        NaN
1   6.0   4.878       3.0        NaN
2   4.0   7.232       1.0  21-SEP-23
3   6.0  10.806       1.0        NaN
4  24.0  15.360       5.0        NaN

Duplicate DataFrame:
   SITE_ID   LOCATION   PARTY DEPT_NAME       SEC_NAME  \
0      461  COSTO KTN   S0068  1S01FMCG  1S0101GROCERY
1      461  COSTO KTN   R0003  1S01FMCG  1S0101GROCERY
2      461  COSTO KTN   A0214  1S01FMCG  1S0101GROCERY
3      461  COSTO KTN   A0214  1S01FMCG  1S0101GROCERY
4      461  COSTO KTN  KAJ001  1S01FMCG  1S0101GROCERY

                        CAT_NAME  PROD_CODE  SU  \
0  1S010115 CANNED / PACKED FISH     731940   1
1             1S010102COFFEE/TEA     775612   0
2              1S010108 BISCUITS     325966   8
3              1S010108 BISCUITS     318460   6
4             1S010102COFFEE/TEA     751620   0

                                  SU_DESCRIPTION      BRAND       BARCODE  \
0              PRINCESS SARDINE CHILLI 5 X 125GM   PRINCESS  2.000007e+12
1            DILMAH ENGLISH BREAKFAST TEA BAG 20     DILMAH  9.312631e+12
2  BRITANNIA GOOD DAY PISTA BADAM 2X8X72GM PROMO  BRITANNIA  6.291008e+12
3       BRITANNIA GOOD DAY CASHEW 2X8X72GM PROMO  BRITANNIA  6.291008e+12
4                      SIBLA DUST TEA BOX 450 GM      SIBLA  2.000007e+12

    SOH   VALUE  AGE_DAYS   SALE_AGE
0   8.0   8.800      19.0        NaN
1   6.0   4.878       3.0        NaN
2   4.0   7.232       1.0  21-SEP-23
3   6.0  10.806       1.0        NaN
4  24.0  15.360       5.0        NaN

In [ ]:
# Specify the number of characters to remove for each column
characters_to_remove = {'DEPT_NAME': 4, 'SEC_NAME': 6, 'CAT_NAME': 8}

# Iterate through the columns and remove the specified number of characters in the copy
for column, num_chars in characters_to_remove.items():
    df_duplicate[column] = df_duplicate[column].str.slice(num_chars)

# Display the updated DataFrame copy
print(df_duplicate.head())

   SITE_ID   LOCATION   PARTY DEPT_NAME SEC_NAME               CAT_NAME  \
0      461  COSTO KTN   S0068      FMCG  GROCERY   CANNED / PACKED FISH
1      461  COSTO KTN   R0003      FMCG  GROCERY             COFFEE/TEA
2      461  COSTO KTN   A0214      FMCG  GROCERY               BISCUITS
3      461  COSTO KTN   A0214      FMCG  GROCERY               BISCUITS
4      461  COSTO KTN  KAJ001      FMCG  GROCERY             COFFEE/TEA

   PROD_CODE  SU                                 SU_DESCRIPTION      BRAND  \
0     731940   1              PRINCESS SARDINE CHILLI 5 X 125GM   PRINCESS
1     775612   0            DILMAH ENGLISH BREAKFAST TEA BAG 20     DILMAH
2     325966   8  BRITANNIA GOOD DAY PISTA BADAM 2X8X72GM PROMO  BRITANNIA
3     318460   6       BRITANNIA GOOD DAY CASHEW 2X8X72GM PROMO  BRITANNIA
4     751620   0                      SIBLA DUST TEA BOX 450 GM      SIBLA

        BARCODE   SOH   VALUE  AGE_DAYS   SALE_AGE
0  2.000007e+12   8.0   8.800      19.0        NaN
1  9.312631e+12   6.0   4.878       3.0        NaN
2  6.291008e+12   4.0   7.232       1.0  21-SEP-23
3  6.291008e+12   6.0  10.806       1.0        NaN
4  2.000007e+12  24.0  15.360       5.0        NaN

In [ ]:
unique_values = df_duplicate['DEPT_NAME'].unique()
print(unique_values)

['FMCG' 'OPSS  AND  FROZEN' 'LIGHT HOUSE HOLD'
 'ELECTRONICS  AND  APPLIANCES' 'FASHION  AND  LIFESTYLE' 'FRESH FOOD'
 'SHOP SUPPORTIVE' 'COMMUNICATION SERVICES' 'ASSETS / EQUIP']

In [ ]:
# Join Column1 and Column2 without any separator
df_duplicate['KEY PROD CODE'] = df_duplicate['PROD_CODE'] + df_duplicate['SU']

In [ ]:
# Assuming you have a DataFrame named 'df' and you want to drop columns 'Column1' and 'Column2'
columns_to_drop = [ 'PROD_CODE', 'SU']

# Use the drop() method to remove the specified columns
df_duplicate.drop(columns=columns_to_drop, inplace=True)

In [ ]:
df_duplicate.columns

Index(['SITE_ID', 'LOCATION', 'PARTY', 'DEPT_NAME', 'SEC_NAME', 'CAT_NAME',
       'SU_DESCRIPTION', 'BRAND', 'BARCODE', 'SOH', 'VALUE', 'AGE_DAYS',
       'SALE_AGE', 'KEY PROD CODE'],
      dtype='object')

In [ ]:
import numpy as np

In [ ]:
#filling na values in the data

new_df = df_duplicate.fillna({
        'SALE_AGE': 'NO SALE DATE',
        'BRAND': 'No brand',
    })
new_df.head()

,SITE_ID,LOCATION,PARTY,DEPT_NAME,SEC_NAME,CAT_NAME,SU_DESCRIPTION,BRAND,BARCODE,SOH,VALUE,AGE_DAYS,SALE_AGE,KEY PROD CODE
0,461,COSTO KTN,S0068,FMCG,GROCERY,CANNED / PACKED FISH,PRINCESS SARDINE CHILLI 5 X 125GM,PRINCESS,2.000007e+12,8.0,8.800,19.0,NO SALE DATE,731941
1,461,COSTO KTN,R0003,FMCG,GROCERY,COFFEE/TEA,DILMAH ENGLISH BREAKFAST TEA BAG 20,DILMAH,9.312631e+12,6.0,4.878,3.0,NO SALE DATE,775612
2,461,COSTO KTN,A0214,FMCG,GROCERY,BISCUITS,BRITANNIA GOOD DAY PISTA BADAM 2X8X72GM PROMO,BRITANNIA,6.291008e+12,4.0,7.232,1.0,21-SEP-23,325974
3,461,COSTO KTN,A0214,FMCG,GROCERY,BISCUITS,BRITANNIA GOOD DAY CASHEW 2X8X72GM PROMO,BRITANNIA,6.291008e+12,6.0,10.806,1.0,NO SALE DATE,318466
4,461,COSTO KTN,KAJ001,FMCG,GROCERY,COFFEE/TEA,SIBLA DUST TEA BOX 450 GM,SIBLA,2.000007e+12,24.0,15.360,5.0,NO SALE DATE,751620

In [ ]:
unique_values = new_df1['DEPT_NAME'].unique()

# Print the unique values
print(unique_values)

['FMCG' 'OPSS  AND  FROZEN' 'LIGHT HOUSE HOLD'
 'ELECTRONICS  AND  APPLIANCES' 'FASHION  AND  LIFESTYLE' 'FRESH FOOD'
 'COMMUNICATION SERVICES' 'ASSETS / EQUIP']

In [ ]:
# List of values to be deleted
values_to_delete = ['HOT FOOD INHOUSE', 'FISHERY (W)', 'GENERAL EXPENSE', 'BUTCHERY (W)', 'UNIFROM', 'HOT FOOD INDUSTRIAL', 'FRUITS AND VEGETABLES(W)']

# Use boolean indexing to filter and keep rows that don't match the values to delete
new_df1 = new_df[~new_df['SEC_NAME'].isin(values_to_delete)]

In [ ]:
# Save the DataFrame to a CSV file
new_df1.to_csv('filtered_data.csv', index=False)

# Download the CSV file to your local machine
from google.colab import files
files.download('filtered_data.csv')

In [ ]:
new_df1.head()

,SITE_ID,LOCATION,PARTY,DEPT_NAME,SEC_NAME,CAT_NAME,SU_DESCRIPTION,BRAND,BARCODE,SOH,VALUE,AGE_DAYS,SALE_AGE,KEY PROD CODE
0,461,COSTO KTN,S0068,FMCG,GROCERY,CANNED / PACKED FISH,PRINCESS SARDINE CHILLI 5 X 125GM,PRINCESS,2.000007e+12,8.0,8.800,19.0,NO SALE DATE,731941
1,461,COSTO KTN,R0003,FMCG,GROCERY,COFFEE/TEA,DILMAH ENGLISH BREAKFAST TEA BAG 20,DILMAH,9.312631e+12,6.0,4.878,3.0,NO SALE DATE,775612
2,461,COSTO KTN,A0214,FMCG,GROCERY,BISCUITS,BRITANNIA GOOD DAY PISTA BADAM 2X8X72GM PROMO,BRITANNIA,6.291008e+12,4.0,7.232,1.0,21-SEP-23,325974
3,461,COSTO KTN,A0214,FMCG,GROCERY,BISCUITS,BRITANNIA GOOD DAY CASHEW 2X8X72GM PROMO,BRITANNIA,6.291008e+12,6.0,10.806,1.0,NO SALE DATE,318466
4,461,COSTO KTN,KAJ001,FMCG,GROCERY,COFFEE/TEA,SIBLA DUST TEA BOX 450 GM,SIBLA,2.000007e+12,24.0,15.360,5.0,NO SALE DATE,751620